name: CD

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Export version information to environment variables
      run: |
        echo "::set-env name=BRANCH::$(make echo_branch)"
        echo "::set-env name=BUILD_USER::$(make echo_build_user)"
        echo "::set-env name=BUILD_DATE::$(make echo_build_date)"

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
