name: My Workflow
on:
  push:
    branches:
    - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: Run lint
      run: |
        GO111MODULE=off GOPATH=$HOME/go go get golang.org/x/lint/golint
        $HOME/go/bin/golint ./...
        go vet ./...
    - name: Build binary
      run: go build -v .
