name: My Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v1
    # - name: Hello world action step
    #   uses: ./.github/actions/hello-world-action
    #   id: hello
    #   with:
    #     who-to-greet: 'Mona the Octocat'
    # # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Build
      uses: go run my_exporter.go
  