name: My Workflow

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.4
    - run: env | sort
    - run: which go
    - run: go get -u golang.org/x/lint/golint
    - run: ls $HOME/go/bin
    - run: golint ./...
      env:
        PATH: $HOME/go/bin:$PATH
    - run: go vet ./...
    - run: go build -v .
