name: My Workflow

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.4
    - run: env | sort
    - run: go get -u golang.org/x/lint/golint
    - run: $HOME/go/bin/golint ./...
    - run: go vet ./...
    - run: go build -v .
