name: My Workflow
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: Run lint
      run: |
        GO111MODULE=off GOPATH=$HOME/go go get golang.org/x/lint/golint
        $HOME/go/bin/golint ./...
        go vet ./...
    - name: Build binary
      run: go build -v .
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: my_exporter
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download binary
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Run OpenIO
      uses: ./.github/actions/openio
    - run: ./build/my_exporter
    

