name: OpenIO
on:
  push:
    branches:
    - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - run: docker help
    - name: Check out code
      uses: actions/checkout@v1
    - name: Run OpenIO
      uses: ./.github/actions/openio
