name: OpenIO
on:
  push:
    branches:
    - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - run: docker image ls
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build binary
      run: |
        go build -v .
        cp ./my_exporter ./.github/actions/openio
    - name: Run OpenIO
      uses: ./.github/actions/openio
